version: "3.8"

services:
  wordpress:
    image: wordpress:6.6-fpm
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: |
        if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
          $_SERVER['HTTPS'] = 'on';
        }
    volumes:
      - wp_data:/var/www/html

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "80"
    restart: unless-stopped

volumes:
  wp_data:
